# Generated by Django 5.1.15 on 2026-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_root',
            field=models.BooleanField(default=False, verbose_name='超级管理员'),
        ),
        migrations.AlterField(
            model_name='roleassignment',
            name='role',
            field=models.CharField(choices=[('president', '会长'), ('vice_president', '副会长'), ('group_leader', '组长'), ('vice_group_leader', '副组长'), ('member', '组员'), ('teacher', '指导老师'), ('sophia_admin', '寰宇智域管理员')], max_length=20, verbose_name='角色'),
        ),
    ]
