# Generated by Django 5.1.15 on 2026-08-15 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hardware2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('grade', models.CharField(blank=True, default='', max_length=20, verbose_name='年级')),
                ('role', models.CharField(choices=[('leader', '组长'), ('vice_leader', '副组长'), ('member', '成员')], default='member', max_length=20, verbose_name='组内身份')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '硬件组成员',
                'verbose_name_plural': '硬件组成员',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HardwareRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='教室')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '硬件组教室',
                'verbose_name_plural': '硬件组教室',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HardwareTableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('layout_type', models.CharField(default='reinstall', max_length=30, verbose_name='布局类型')),
                ('fields_json', models.JSONField(default=list, verbose_name='字段定义')),
                ('use_room_source', models.BooleanField(default=True, verbose_name='引用教室数据')),
                ('use_member_source', models.BooleanField(default=False, verbose_name='引用成员数据')),
            ],
            options={
                'verbose_name': '硬件组表模板',
                'verbose_name_plural': '硬件组表模板',
            },
        ),
        migrations.CreateModel(
            name='HardwareDynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='表名')),
                ('use_room_source', models.BooleanField(default=False, verbose_name='引用教室数据')),
                ('use_member_source', models.BooleanField(default=False, verbose_name='引用成员数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_tables', to='accounts.hardware2026board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hw_dynamic_tables', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hw_dynamic_tables', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hardwaretabletemplate')),
            ],
            options={
                'verbose_name': '硬件组动态表',
                'verbose_name_plural': '硬件组动态表',
            },
        ),
        migrations.CreateModel(
            name='HardwareDynamicRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='行数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hw_dynamic_rows', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hw_dynamic_rows', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='accounts.hardwaredynamictable')),
            ],
            options={
                'verbose_name': '硬件组动态行',
                'verbose_name_plural': '硬件组动态行',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HardwareDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='字段键')),
                ('label', models.CharField(max_length=100, verbose_name='字段名')),
                ('field_type', models.CharField(max_length=30, verbose_name='字段类型')),
                ('options_json', models.JSONField(blank=True, default=list, verbose_name='选项')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('source_type', models.CharField(blank=True, default='', max_length=20, verbose_name='来源类型')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounts.hardwaredynamictable')),
            ],
            options={
                'verbose_name': '硬件组动态字段',
                'verbose_name_plural': '硬件组动态字段',
                'ordering': ['order', 'id'],
            },
        ),
    ]
